.\"
.\" Man page for dcraw
.\"
.\" Copyright (c) 2009 by David Coffin
.\"
.\" You may distribute without restriction.
.\"
.\" David Coffin
.\" dcoffin a cybercom o net
.\" http://www.cybercom.net/~dcoffin
.\"
.TH dcraw 1 "2009 年 3 月 3 日"
.LO 1
.SH 名　称
dcraw - 命令行界面 raw 影像解码工具
.SH 总　览
.B dcraw
[\fI参数\fR]... [\fI图档路径\fR]...
.SH 概　要
.B dcraw
解码原始影像档案，显示图档之元数据 (metadata) 以及产生预览图片。
.SH 一般选项
.TP
.B -v
在除了警告与错误信息外并显示额外的执行情报。
.TP
.B -c
将解码后图片与预览图片资料送至标准输出埠 (STDOUT)
.TP
.B -e
自原始影像档案中解出由相机产生的预览图片。视相机厂牌型号的不同，产生的图档有可能是 JPEG 或 PPM 格式。
.TP
.B -z
将产生之档案的最后存取时间设定为照片的实际拍摄时间。
.TP
.B -i
仅辨识输入档案的格式而不进行解码。如果
.B dcraw
可以支援该种档案，本命令结束时的状态码会是 0，反之如果辨识失败状态码则是 1。
.B -i -v
则可以显示图档之元数据 (metadata)。
.TP
.B ""
请注意
.B dcraw
不能解码 JPEG 格式档案！
.SH 影像修补选项
.TP
.B -P deadpixels.txt
忽略 .badpixels 参数，自此档案中读取损坏感应元件之资料列表
参见
.B 相关档案
中之档案格式叙述
.TP
.B -K darkframe.pgm
使用黑框抵消法来消除影像杂讯。如欲产生黑框影像，请将相机镜头盖上后拍摄一张原始影像照片，
并使用
.B dcraw -D -4 -j -t 0 
命令来产生参考档案。
.TP
.B -k 黑暗度
当影像中的阴影显得模糊时，你可以试著增加黑暗度来改善这个问题。
你可以利用上述命令来产生参考档案后，再利用下述命令来测量黑暗度：
.B pamsumm -mean
.TP
.B -S 饱和度
当影像中的亮处显得发红时，你可以试著减低饱和度来改善问题。
请先到一个明亮的地方拍张照片，再利用下述命令来度量饱和度的参考值：
.B dcraw -D -4 -j -c
photo.raw
.B | pamsumm -max
.TP
.B ""
在一般的情况下，预设的黑暗度与饱和度应该是不需调整的。
.TP
.B -n 杂讯消除临界值
利用微波法来消除杂讯同时保存影像细节。
杂讯消除临界值我们建议使用 100 至 1000 之间的数值。
.TP
.B -C 红色缩放倍数 蓝色缩放倍数
根据参数来缩放红色与蓝色图层。通常倍数是在 0.999 至 1.001 之间，
此命令可以透过红蓝图层的缩放来消除影像的色像差。
.TP
.B -H 0
将影像中过亮部份改成纯白色。（预设功能）
.TP
.B -H 1
影像中过亮部份以淡粉红色阶调来取代。
.TP
.B -H 2
混合过曝与正常曝光值来产生均匀的渐层白色。
.TP
.B -H 3+
重建影像中高亮度部份的色彩。参数值较低时会比较偏向采用白色来取代高亮度部份的色彩；
高数值时则会使用颜色渐层来取代。建议尝试您先设定成
.B -H 5
来进行试验。如果对于效果不满意，可再试试先用
.B -H 9
来进行转换后，在影像编辑软体中把带有颜色的高亮度部份除去后，再与一张使用
.B -H 3
参数来转换的同一图档进行合并。
.SH 色彩选项
在一般状态下
.B dcraw
程式使用固定的白平衡值，这个数值是经由测量在 D65 灯光下的标准色表所得。
.TP
.B -w
使用相机所指定的白平衡值。
如果在档案中找不到此项资料，显示警告信息并改用其他方式调整白平衡。
.TP
.B -a
利用整个影像的平均值来计算白平衡。
.TP
.B -A 左方座标 上方座标 宽度 高度
利用一个矩形区域的影像平均值来计算白平衡。
这项功能首先会执行
.B dcraw -j -t 0
接著选择一个有中性灰色的区域来进行计算。
.TP
.B -r 系数0 系数1 系数2 系数3
使用自定白平衡值。
上述四个参数可以拷贝自以下命令的输出：
.BR dcraw\ -v .
.TP
.BR +M " or " -M
使用或是舍弃影像档案中的色彩矩阵资料。
如果一并使用
.B -w
选项，则预设值为
.B +M
否则将会使用
.B -M
这个参数只会影响 Olympus、Leaf 以及 Phase One 等品牌相机所拍摄的照片。
.TP
.B -o [0-5]
选定当
.B -p
选项没有使用时所输出的色域：

.B \t0
\ \原始影像色彩 (各厂牌均有不同值)
.br
.B \t1
\ \ sRGB D65 (预设值)
.br
.B \t2
\ \ Adobe RGB (1998) D65
.br
.B \t3
\ \ Wide Gamut RGB D65
.br
.B \t4
\ \ Kodak ProPhoto RGB D65
.br
.B \t5
\ \ XYZ
.TP
.BR -p\ camera.icm \ [\  -o\ output.icm \ ]
利用 ICC 描述档案来定义相机的输入以及输出 colorspace。(预设的 profile 值为 sRGB)
.TP
.B -p embed
使用嵌在原始影像档案中的 ICC 描述来决定 colorspace
.SH 内插运算选项
.TP
.B -d
将原始影像档案内容以灰阶方式解码，不使用内插法来改善影像品质。
这个模式最适合翻拍文件
.TP
.B -D
此模式与
.B -d
一样会输出灰阶影像，
但是影像解码过程完全不经过任何处理。
.TP
.B -h
输出影像的长宽减半，相对的解码速度也会比
.B -q 0
快上一倍。
.TP
.B -q 0
使用品质略逊，但速度较快的双线性 (bilinear) 内插法来进行影像的解码。
.TP
.B -q 1
使用变数渐层 (Variable Number of Gradients, VNG) 内插法来进行影像的解码。
.TP
.B -q 2
使用像素图样组群 (Patterned Pixel Grouping, PPG) 内插法。
.TP
.B -q 3
使用 Adaptive Homogeneity-Directed (AHD) 内插法来进行影像的解码。
.TP
.B -f
在进行内插法演算时将 RGB 当成四种颜色。 如果利用 VNG 或是 AHD 内插法来产生影像结果
出现格状杂讯的话，请加上这个选项来减少杂讯。
.TP
.B -m 重复运算次数
在使用内插法产生中介数值后，在红绿与蓝绿色频上重复利用 3x3 大小的中间值滤镜来消除色彩杂讯。
.SH 输出选项
在一般情况下
.B dcraw
会产生利用八位元取样、采用 BT.709 gamma 曲线、根据平均值所计算之全白色值、以及没有元数据的 PGM/PPM/PAM 档案。
.TP
.B -W
忽略平均值计算所得之全白色值，使用参数指定的全白色值。
.TP
.B -b 亮度
将全白色值除以这个参数，预设值为 1.0。
.TP
.B -g 次方 斜率极大值
设定 gamma 曲线值，预设值为 BT.709
.RB ( -g\ 2.222\ 4.5 ).
如果你想要使用 sRGB 色域的 gamma 曲线，请使用
.BR -g\ 2.4\ 12.92 .
如欲使用简单乘方曲线，请将斜率极大值设定成 0
.TP
.B -4
输出 16 位元线性档案（固定全白色值，不改变 gamma 值）
.TP
.B -T
输出 TIFF 格式（附元数据）的影像档案。
.TP
.B -t [0-7,90,180,270]
旋转图片。此命令的预设值是根据相机之方向感应器资料而定。使用
.B -t 0
命令则可以取消自动旋转功能。
.TP
.B -j
使用 Fuji\ Super\ CCD 的数码相机因为像素不是正方形，在电脑萤幕上无法以正确的长宽比显示。
使用这个参数会产生转 45 度角的影像，如此可以确保每个像素都对应到一个感应元件。
.TP
.BR "-s [0..N-1]" " or " "-s all"
如果在一个影像档案里夹有 N 个 RAW 影像档案，利用此参数可以选择要解码那个影像。
以 Fuji\ Super\ CCD\ SR 相机为例，每个 RAW 影像档案里都包含有两个影像，
其中一个是专门记录高亮度区域的资料。
.SH 相关档案
.TP
\:./.badpixels, ../.badpixels, ../../.badpixels, ...
列出相机感光元件上损坏的感应元件（dead pixels）。
.B dcraw
将会参考这个档案在解码时避开这些像素。这种档案的格式为：
.sp 1
.nf
 962   91 1028350000  # 该感光元件在 2001 年八月一日至四日之间出现问题
1285 1067 0           # 不确定此感光元件损坏的确实时间
.fi
.sp 1
这些座标是以照片转向与被裁切之前的状态为准。请使用
.B dcraw -j -t 0
命令来找寻有问题像素的座标。
.SH "参　见"
.BR pgm (5),
.BR ppm (5),
.BR pam (5),
.BR pamsumm (1),
.BR pnmgamma (1),
.BR pnmtotiff (1),
.BR pnmtopng (1),
.BR gphoto2 (1),
.BR cjpeg (1),
.BR djpeg (1)
.SH 作　者
本软体由 David Coffin 制作，电邮地址： dcoffin a cybercom o net
