.\"
.\" Man page for dcraw
.\"
.\" Copyright (c) 2009 by David Coffin
.\"
.\" You may distribute without restriction.
.\"
.\" David Coffin
.\" dcoffin a cybercom o net
.\" http://www.cybercom.net/~dcoffin
.\"
.TH dcraw 1 "2009 年 3 月 3 日"
.LO 1
.SH 名　稱
dcraw - 指令界面原始影像解碼工具
.SH 總　覽
.B dcraw
[\fI參數\fR]... [\fI圖檔路徑\fR]...
.SH 概　要
.B dcraw
解碼原始影像檔案，顯示圖檔之詮釋資料 (metadata) 以及產生預覽圖片。
.SH 一般選項
.TP
.B -v
在除了警告與錯誤訊息外並顯示額外的執行資訊。
.TP
.B -c
將解碼後圖片與預覽圖片資料送至標準輸出埠 (STDOUT)
.TP
.B -e
自原始影像檔案中解出由相機產生的預覽圖片。視相機廠牌型號的不同，產生的圖檔有可能是 JPEG 或 PPM 格式。
.TP
.B -z
將產生之檔案的最後存取時間設定為照片的實際拍攝時間。
.TP
.B -i
僅辨識輸入檔案的格式而不進行解碼。如果
.B dcraw
可以支援該種檔案，本指令結束時的狀態碼會是 0，反之如果辨識失敗狀態碼則是 1。
.B -i -v
則可以顯示圖檔之詮釋資料 (metadata)。
.TP
.B ""
請注意
.B dcraw
不能解碼 JPEG 格式檔案！
.SH 影像修補選項
.TP
.B -P deadpixels.txt
忽略 .badpixels 參數，自此檔案中讀取損壞感應元件之資料列表
參見
.B 相關檔案
中之檔案格式敘述
.TP
.B -K darkframe.pgm
使用黑框抵消法來消除影像雜訊。如欲產生黑框影像，請將相機鏡頭蓋上後拍攝一張原始影像照片，
並使用
.B dcraw -D -4 -j -t 0
指令來產生參考檔案。
.TP
.B -k 黑暗度
當影像中的陰影顯得模糊時，你可以試著增加黑暗度來改善這個問題。
你可以利用上述指令來產生參考檔案後，再利用下述指令來測量黑暗度：
.B pamsumm -mean
.TP
.B -S 飽和度
當影像中的亮處顯得發紅時，你可以試著減低飽和度來改善問題。
請先到一個明亮的地方拍張照片，再利用下述指令來度量飽和度的參考值：
.B dcraw -D -4 -j -c
photo.raw
.B | pamsumm -max
.TP
.B ""
在一般的情況下，預設的黑暗度與飽和度應該是不需調整的。
.TP
.B -n 雜訊消除臨界值
利用微波法來消除雜訊同時保存影像細節。
雜訊消除臨界值我們建議使用 100 至 1000 之間的數值。
.TP
.B -C 紅色縮放倍數 藍色縮放倍數
根據參數來縮放紅色與藍色圖層。通常倍數是在 0.999 至 1.001 之間，
此指令可以透過紅藍圖層的縮放來消除影像的色像差。
.TP
.B -H 0
將影像中過亮部份改成純白色。（預設功能）
.TP
.B -H 1
影像中過亮部份以淡粉紅色階調來取代。
.TP
.B -H 2
混合過曝與正常曝光值來產生均勻的漸層白色。
.TP
.B -H 3+
重建影像中高亮度部份的色彩。參數值較低時會比較偏向採用白色來取代高亮度部份的色彩；
高數值時則會使用顏色漸層來取代。建議嘗試您先設定成
.B -H 5
來進行試驗。如果對於效果不滿意，可再試試先用
.B -H 9
來進行轉換後，在影像編輯軟體中把帶有顏色的高亮度部份除去後，再與一張使用
.B -H 3
參數來轉換的同一圖檔進行合併。
.SH 色彩選項
在一般狀態下
.B dcraw
程式使用固定的白平衡值，這個數值是經由測量在 D65 燈光下的標準色表所得。
.TP
.B -w
使用相機所指定的白平衡值。
如果在檔案中找不到此項資料，顯示警告訊息並改用其他方式調整白平衡。
.TP
.B -a
利用整個影像的平均值來計算白平衡。
.TP
.B -A 左方座標 上方座標 寬度 高度
利用一個矩形區域的影像平均值來計算白平衡。
這項功能首先會執行
.B dcraw -j -t 0
接著選擇一個有中性灰色的區域來進行計算。
.TP
.B -r 係數0 係數1 係數2 係數3
使用自定白平衡值。
上述四個參數可以拷貝自以下指令的輸出：
.BR dcraw\ -v .
.TP
.BR +M " or " -M
使用或是捨棄影像檔案中的 color matrix 資料。
如果一併使用
.B -w
選項，則預設值為
.B +M
否則將會使用
.B -M
這個參數只會影響 Olympus、Leaf 以及 Phase One 等品牌相機所拍攝的照片。
.TP
.B -o [0-5]
選定當
.B -p
選項沒有使用時所輸出的色域：

.B \t0
\ \原始影像色彩 (各廠牌均有不同值)
.br
.B \t1
\ \ sRGB D65 (預設值)
.br
.B \t2
\ \ Adobe RGB (1998) D65
.br
.B \t3
\ \ Wide Gamut RGB D65
.br
.B \t4
\ \ Kodak ProPhoto RGB D65
.br
.B \t5
\ \ XYZ
.TP
.BR -p\ camera.icm \ [\  -o\ output.icm \ ]
利用 ICC 描述檔案來定義相機的輸入以及輸出 colorspace。(預設的 profile 值為 sRGB)
.TP
.B -p embed
使用嵌在原始影像檔案中的 ICC 描述來決定 colorspace
.SH 內插運算選項
.TP
.B -d
將原始影像檔案內容以灰階方式解碼，不使用內插法來改善影像品質。
這個模式最適合翻拍文件
.TP
.B -D
此模式與
.B -d
一樣會輸出灰階影像，
但是影像解碼過程完全不經過任何處理。
.TP
.B -h
輸出影像的長寬減半，相對的解碼速度也會比
.B -q 0
快上一倍。
.TP
.B -q 0
使用品質略遜，但速度較快的雙線性 (bilinear) 內插法來進行影像的解碼。
.TP
.B -q 1
使用變數漸層 (Variable Number of Gradients, VNG) 內插法來進行影像的解碼。
.TP
.B -q 2
使用像素圖樣組群 (Patterned Pixel Grouping, PPG) 內插法。
.TP
.B -q 3
使用 Adaptive Homogeneity-Directed (AHD) 內插法來進行影像的解碼。
.TP
.B -f
在進行內插法演算時將 RGB 當成四種顏色。 如果利用 VNG 或是 AHD 內插法來產生影像結果
出現格狀雜訊的話，請加上這個選項來減少雜訊。
.TP
.B -m 重複運算次數
在使用內插法產生中介數值後，在紅綠與藍綠色頻上重複利用 3x3 大小的中間值濾鏡來消除色彩雜訊。
.SH 輸出選項
在一般情況下
.B dcraw
會產生利用八位元取樣、採用 BT.709 gamma 曲線、根據平均值所計算之全白色值、以及沒有詮釋資料的 PGM/PPM/PAM 檔案。
.TP
.B -W
忽略平均值計算所得之全白色值，使用參數指定的全白色值。
.TP
.B -b 亮度
將全白色值除以這個參數，預設值為 1.0。
.TP
.B -g 次方 斜率極大值
設定 gamma 曲線值，預設值為 BT.709
.RB ( -g\ 2.222\ 4.5 ).
如果你想要使用 sRGB 色域的 gamma 曲線，請使用
.BR -g\ 2.4\ 12.92 .
如欲使用簡單乘方曲線，請將斜率極大值設定成 0
.TP
.B -4
輸出 16 位元線性檔案（固定全白色值，不改變 gamma 值）
.TP
.B -T
輸出 TIFF 格式（附詮釋資料）的影像檔案。
.TP
.B -t [0-7,90,180,270]
旋轉圖片。此指令的預設值是根據相機之方向感應器資料而定。使用
.B -t 0
指令則可以取消自動旋轉功能。
.TP
.B -j
使用 Fuji\ Super\ CCD 的數位相機因為像素不是正方形，在電腦螢幕上無法以正確的長寬比顯示。
使用這個參數會產生轉 45 度角的影像，如此可以確保每個像素都對應到一個感應元件。
.TP
.BR "-s [0..N-1]" " or " "-s all"
如果在一個影像檔案裡夾有 N 個 RAW 影像檔案，利用此參數可以選擇要解碼那個影像。
以 Fuji\ Super\ CCD\ SR 相機為例，每個 RAW 影像檔案裡都包含有兩個影像，
其中一個是專門記錄高亮度區域的資料。
.SH 相關檔案
.TP
\:./.badpixels, ../.badpixels, ../../.badpixels, ...
列出相機感光元件上損壞的感應元件（dead pixels）。
.B dcraw
將會參考這個檔案在解碼時避開這些像素。這種檔案的格式為：
.sp 1
.nf
 962   91 1028350000  # 該感光元件在 2001 年八月一日至四日之間出現問題
1285 1067 0           # 不確定此感光元件損壞的確實時間
.fi
.sp 1
這些座標是以照片轉向與被裁切之前的狀態為準。請使用
.B dcraw -j -t 0
指令來找尋有問題的像素的座標。
.SH "參　見"
.BR pgm (5),
.BR ppm (5),
.BR pam (5),
.BR pamsumm (1),
.BR pnmgamma (1),
.BR pnmtotiff (1),
.BR pnmtopng (1),
.BR gphoto2 (1),
.BR cjpeg (1),
.BR djpeg (1)
.SH 作　者
本軟體由 David Coffin 製作，電郵信箱： dcoffin a cybercom o net
