on:
  workflow_dispatch:
  schedule:
  - cron: 0 6 * * 1

name: releases of dependencies
jobs:
  dependency_releases:
    runs-on: windows-2022

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Clone repositories
      shell: cmd
      run: CloneRepositories.cmd https://github.com/ImageMagick shallow

    - name: Check for new releases of dependencies
      shell: cmd
      run: CheckReleases.cmd
